In [1]:
import numpy as np
import pandas as pd

In [2]:
date= pd.read_csv('orders.csv')
time= pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   str
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), str(1)
memory usage: 31.4 KB

In [6]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   str
 1   msg     1000 non-null   str
dtypes: str(2)
memory usage: 15.8 KB

# Working with Dates:

In [7]:
date['date'] = pd.to_datetime(date['date'])
time['date'] = pd.to_datetime(time['date'])

In [8]:
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[us]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[us](1), int64(3)
memory usage: 31.4 KB

In [9]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[us]
 1   msg     1000 non-null   str
dtypes: datetime64[us](1), str(1)
memory usage: 15.8 KB

# 1. Extract Year:

In [10]:
date['date_year'] = date['date'].dt.year
date.sample(5)

          date  product_id  city_id  orders  date_year
733 2019-07-10        3081       30       5       2019
923 2018-11-23        1073        2       1       2018
250 2019-02-16        2611       13      11       2019
397 2019-06-25        6435       13       1       2019
166 2018-10-11        3946       30       9       2018

# 2. Extract Month_number:

In [11]:
date['date_month_no'] = date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

# 3. Extract Month_name:

In [12]:
date['date_month_name'] = date['date'].dt.month_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

# 4. Extract Day:

In [13]:
date['date_day'] = date['date'].dt.day
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

# 5. Extract Day of Week:

In [14]:
date['date_dow'] = date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

# 6. Extract Day of week name:

In [15]:
date['date_dow_name'] = date['date'].dt.day_name()
date.drop(columns=['product_id','city_id','orders'])
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday

# 7. Checking if it's Weekend?

In [16]:
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday','Saturday']),1,0)
date.drop(columns=['product_id','city_id','orders'])
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1

# 8. Extract week of the year:

In [19]:
date['date_week']= date['date'].dt.isocalendar().week
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1

# 9. Extract Quarter:

In [20]:
date['quarter'] = date['date'].dt.quarter
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1

# 10. Extract Semester:

In [21]:
date['semester'] = np.where(date['quarter'].isin([1,2]),1,2)
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1,1

# Extract Time elapsed between Dates:

In [22]:
import datetime

In [24]:
today = datetime.datetime.today()
today

datetime.datetime(2026, 7, 17, 12, 27, 44, 450706)

In [25]:
today - date['date']

0     2411 days 12:27:44.450706
1     2893 days 12:27:44.450706
2     2824 days 12:27:44.450706
3     2526 days 12:27:44.450706
4     2749 days 12:27:44.450706
                 ...
995   2839 days 12:27:44.450706
996   2780 days 12:27:44.450706
997   2628 days 12:27:44.450706
998   2693 days 12:27:44.450706
999   2467 days 12:27:44.450706
Name: date, Length: 1000, dtype: timedelta64[us]

In [26]:
(today - date['date']).dt.days

0      2411
1      2893
2      2824
3      2526
4      2749
       ...
995    2839
996    2780
997    2628
998    2693
999    2467
Name: date, Length: 1000, dtype: int64

In [29]:
# Months Passed:

# today is a Python datetime.datetime object, and to_period() is a pandas method, not a Python datetime method.
# Convert today to a pandas Timestamp
date['months_passed']= (pd.Timestamp(today).to_period('M') - date['date'].dt.to_period('M')).apply(lambda x: x.n)
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester,months_passed
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4,2,79
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3,2,95
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4,2,93
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3,2,83
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1,1,90

In [30]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second
time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

# 1. Extract time part :

In [31]:
time['time'] = time['date'].dt.time
time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

# Time Difference :

In [32]:
today - time['date']

0     4597 days 11:37:44.450706
1     4461 days 12:47:44.450706
2     4947 days 12:06:44.450706
3     4249 days 11:56:44.450706
4     4646 days 13:16:44.450706
                 ...
995   5236 days 11:37:44.450706
996   4557 days 13:13:44.450706
997   5022 days 12:50:44.450706
998   5138 days 12:53:44.450706
999   4410 days 13:02:44.450706
Name: date, Length: 1000, dtype: timedelta64[us]

In [34]:
# In seconds:
(today - time['date'])/np.timedelta64(1,'s')

0      3.972227e+08
1      3.854765e+08
2      4.274644e+08
3      3.671566e+08
4      4.014622e+08
           ...
995    4.524323e+08
996    3.937724e+08
997    4.339470e+08
998    4.439696e+08
999    3.810710e+08
Name: date, Length: 1000, dtype: float64

In [35]:
# In minutes:
(today - time['date'])/ np.timedelta64(1,'m')

0      6.620378e+06
1      6.424608e+06
2      7.124407e+06
3      6.119277e+06
4      6.691037e+06
           ...
995    7.540538e+06
996    6.562874e+06
997    7.232451e+06
998    7.399494e+06
999    6.351183e+06
Name: date, Length: 1000, dtype: float64

In [36]:
# In hours:
(today - time['date'])/ np.timedelta64(1,'h')

0      110339.629014
1      107076.795681
2      118740.112347
3      101987.945681
4      111517.279014
           ...
995    125675.629014
996    109381.229014
997    120540.845681
998    123324.895681
999    105853.045681
Name: date, Length: 1000, dtype: float64