In [82]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression

In [83]:
df= np.round(pd.read_csv('50_Startups.csv')[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)
np.random.seed(9)
df = df.sample(5)
df

    R&D Spend  Administration  Marketing Spend  Profit
21        8.0            15.0             30.0    11.0
37        4.0             5.0             20.0     9.0
2        15.0            10.0             41.0    19.0
14       12.0            16.0             26.0    13.0
44        2.0            15.0              3.0     7.0

In [84]:
df = df.iloc[:, 0:-1]

In [85]:
df

    R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        4.0             5.0             20.0
2        15.0            10.0             41.0
14       12.0            16.0             26.0
44        2.0            15.0              3.0

In [86]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[-1,-1] = np.nan

In [87]:
df.head()

    R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        NaN             5.0             20.0
2        15.0            10.0             41.0
14       12.0             NaN             26.0
44        2.0            15.0              NaN

In [88]:
# Step1: Impute all missing values with mean of respective col
df0 = pd.DataFrame()
df0['R&D Speed'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())

In [89]:
df0

    R&D Speed  Administration  Marketing Spend
21       8.00           15.00            30.00
37       9.25            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.25            26.00
44       2.00           15.00            29.25

In [90]:
df1 = df0.copy()
df1.iloc[1,0] = np.nan
df1

    R&D Speed  Administration  Marketing Spend
21        8.0           15.00            30.00
37        NaN            5.00            20.00
2        15.0           10.00            41.00
14       12.0           11.25            26.00
44        2.0           15.00            29.25

In [91]:
# Use first 3 rows to build a model and use the last for prediction
X = df1.iloc[[0,2,3,4],1:3]
X

    Administration  Marketing Spend
21           15.00            30.00
2            10.00            41.00
14           11.25            26.00
44           15.00            29.25

In [92]:
y= df1.iloc[[0,2,3,4],0]
y

21     8.0
2     15.0
14    12.0
44     2.0
Name: R&D Speed, dtype: float64

In [93]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[1,1:].values.reshape(1,2))

/home/zaid/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([23.14158651])

In [94]:
df1.iloc[1,0] = 23.14

In [95]:
df1

    R&D Speed  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.14            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.25            26.00
44       2.00           15.00            29.25

In [96]:
# Remove the col2 imputed value:
df1.iloc[3,1] = np.nan
df1

    R&D Speed  Administration  Marketing Spend
21       8.00            15.0            30.00
37      23.14             5.0            20.00
2       15.00            10.0            41.00
14      12.00             NaN            26.00
44       2.00            15.0            29.25

In [97]:
# Use the last three rows to build a model and use the first for prediction:
X = df1.iloc[[0,1,2,4],[0,2]]
X

    R&D Speed  Marketing Spend
21       8.00            30.00
37      23.14            20.00
2       15.00            41.00
44       2.00            29.25

In [98]:
y = df.iloc[[0,1,2,4],1]
y

21    15.0
37     5.0
2     10.0
44    15.0
Name: Administration, dtype: float64

In [99]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

/home/zaid/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([11.06331285])

In [100]:
df1.iloc[3,1] = 11.06

In [101]:
df1

    R&D Speed  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.14            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.06            26.00
44       2.00           15.00            29.25

In [102]:
# Remove the col3 imputed value
df1.iloc[4,-1] = np.nan

df1

    R&D Speed  Administration  Marketing Spend
21       8.00           15.00             30.0
37      23.14            5.00             20.0
2       15.00           10.00             41.0
14      12.00           11.06             26.0
44       2.00           15.00              NaN

In [103]:
# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[0:4,0:2]
X

    R&D Speed  Administration
21       8.00           15.00
37      23.14            5.00
2       15.00           10.00
14      12.00           11.06

In [104]:
y = df1.iloc[0:4,-1]
y

21    30.0
37    20.0
2     41.0
14    26.0
Name: Marketing Spend, dtype: float64

In [105]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[4,0:2].values.reshape(1,2))

/home/zaid/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([31.56351448])

In [106]:
df1.iloc[4,-1] = 31.56

In [107]:
# After 1st Iteration
df1

    R&D Speed  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.14            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.06            26.00
44       2.00           15.00            31.56

In [108]:
# Subtract 0th iteration from 1st iteration

df1 - df0

    R&D Speed  Administration  Marketing Spend
21       0.00            0.00             0.00
37      13.89            0.00             0.00
2        0.00            0.00             0.00
14       0.00           -0.19             0.00
44       0.00            0.00             2.31

In [109]:
df2 = df1.copy()

df2.iloc[1,0] = np.nan

df2

    R&D Speed  Administration  Marketing Spend
21        8.0           15.00            30.00
37        NaN            5.00            20.00
2        15.0           10.00            41.00
14       12.0           11.06            26.00
44        2.0           15.00            31.56

In [110]:
X = df2.iloc[[0,2,3,4],1:3]
y = df2.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[1,1:].values.reshape(1,2))

/home/zaid/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([23.78627207])

In [111]:
df2.iloc[1,0] = 23.78

In [112]:
df2.iloc[3,1] = np.nan
X = df2.iloc[[0,1,2,4],[0,2]]
y = df2.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))

/home/zaid/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([11.22020174])

In [113]:
df2.iloc[3,1] = 11.22

In [114]:
df2.iloc[4,-1] = np.nan

X = df2.iloc[0:4,0:2]
y = df2.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[4,0:2].values.reshape(1,2))

/home/zaid/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([38.87979054])

In [115]:
df2.iloc[4,-1] = 31.56

In [116]:
df2

    R&D Speed  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.78            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.22            26.00
44       2.00           15.00            31.56

In [117]:
df2-df1

    R&D Speed  Administration  Marketing Spend
21       0.00            0.00              0.0
37       0.64            0.00              0.0
2        0.00            0.00              0.0
14       0.00            0.16              0.0
44       0.00            0.00              0.0

In [118]:
df3 = df2.copy()

df3.iloc[1,0] = np.nan

df3

    R&D Speed  Administration  Marketing Spend
21        8.0           15.00            30.00
37        NaN            5.00            20.00
2        15.0           10.00            41.00
14       12.0           11.22            26.00
44        2.0           15.00            31.56

In [119]:
X = df3.iloc[[0,2,3,4],1:3]
y = df3.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[1,1:].values.reshape(1,2))

/home/zaid/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([24.57698058])

In [120]:
df3.iloc[1,0] = 24.57

In [121]:
df3.iloc[3,1] = np.nan
X = df3.iloc[[0,1,2,4],[0,2]]
y = df3.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[3,[0,2]].values.reshape(1,2))

/home/zaid/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([11.37282844])

In [122]:
df3.iloc[3,1] = 11.37

In [123]:
df3.iloc[4,-1] = np.nan

X = df3.iloc[0:4,0:2]
y = df3.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[4,0:2].values.reshape(1,2))

/home/zaid/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([45.53976417])

In [124]:
df3.iloc[4,-1] = 45.53

In [125]:
df2.iloc[3,1] = 11.22

In [126]:
df3

    R&D Speed  Administration  Marketing Spend
21       8.00           15.00            30.00
37      24.57            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.37            26.00
44       2.00           15.00            45.53

In [127]:
df3 - df2

    R&D Speed  Administration  Marketing Spend
21       0.00            0.00             0.00
37       0.79            0.00             0.00
2        0.00            0.00             0.00
14       0.00            0.15             0.00
44       0.00            0.00            13.97

# Through Looping:

In [128]:
df= np.round(pd.read_csv('50_Startups.csv')[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)
np.random.seed(9)
df = df.sample(5)
df

    R&D Spend  Administration  Marketing Spend  Profit
21        8.0            15.0             30.0    11.0
37        4.0             5.0             20.0     9.0
2        15.0            10.0             41.0    19.0
14       12.0            16.0             26.0    13.0
44        2.0            15.0              3.0     7.0

In [129]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

imp = IterativeImputer(random_state=0)

df_imputed = imp.fit_transform(df)

In [130]:
df_imputed

array([[ 8., 15., 30., 11.],
       [ 4.,  5., 20.,  9.],
       [15., 10., 41., 19.],
       [12., 16., 26., 13.],
       [ 2., 15.,  3.,  7.]])

In [131]:
df.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
Profit             0
dtype: int64

In [132]:
df.loc[df.index[0], 'R&D Spend'] = np.nan
df.loc[df.index[2], 'Administration'] = np.nan
df.loc[df.index[4], 'Marketing Spend'] = np.nan

In [133]:
df

    R&D Spend  Administration  Marketing Spend  Profit
21        NaN            15.0             30.0    11.0
37        4.0             5.0             20.0     9.0
2        15.0             NaN             41.0    19.0
14       12.0            16.0             26.0    13.0
44        2.0            15.0              NaN     7.0

In [134]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

imp = IterativeImputer(random_state=0)

df_imputed = pd.DataFrame(
    imp.fit_transform(df),
    columns=df.columns,
    index=df.index
)

In [135]:
print("Original DataFrame")
print(df)

print("\nImputed DataFrame")
print(df_imputed)

Original DataFrame
    R&D Spend  Administration  Marketing Spend  Profit
21        NaN            15.0             30.0    11.0
37        4.0             5.0             20.0     9.0
2        15.0             NaN             41.0    19.0
14       12.0            16.0             26.0    13.0
44        2.0            15.0              NaN     7.0

Imputed DataFrame
    R&D Spend  Administration  Marketing Spend  Profit
21   7.552527       15.000000        30.000000    11.0
37   4.000000        5.000000        20.000000     9.0
2   15.000000       28.937071        41.000000    19.0
14  12.000000       16.000000        26.000000    13.0
44   2.000000       15.000000        36.741477     7.0

In [136]:
df_original = df.copy()

In [137]:
print(df_original)
print(df_imputed)

    R&D Spend  Administration  Marketing Spend  Profit
21        NaN            15.0             30.0    11.0
37        4.0             5.0             20.0     9.0
2        15.0             NaN             41.0    19.0
14       12.0            16.0             26.0    13.0
44        2.0            15.0              NaN     7.0
    R&D Spend  Administration  Marketing Spend  Profit
21   7.552527       15.000000        30.000000    11.0
37   4.000000        5.000000        20.000000     9.0
2   15.000000       28.937071        41.000000    19.0
14  12.000000       16.000000        26.000000    13.0
44   2.000000       15.000000        36.741477     7.0

In [138]:
for i in [1, 2, 5, 10]:
    imp = IterativeImputer(max_iter=i, random_state=0)

    df_imp = pd.DataFrame(
        imp.fit_transform(df),
        columns=df.columns
    )

    print(f"\nmax_iter = {i}")
    print(df_imp)

max_iter = 1
   R&D Spend  Administration  Marketing Spend  Profit
0   7.552529       15.000000        30.000000    11.0
1   4.000000        5.000000        20.000000     9.0
2  15.000000       28.937029        41.000000    19.0
3  12.000000       16.000000        26.000000    13.0
4   2.000000       15.000000        36.741459     7.0

max_iter = 2
   R&D Spend  Administration  Marketing Spend  Profit
0   7.552527       15.000000        30.000000    11.0
1   4.000000        5.000000        20.000000     9.0
2  15.000000       28.937071        41.000000    19.0
3  12.000000       16.000000        26.000000    13.0
4   2.000000       15.000000        36.741477     7.0

max_iter = 5
   R&D Spend  Administration  Marketing Spend  Profit
0   7.552527       15.000000        30.000000    11.0
1   4.000000        5.000000        20.000000     9.0
2  15.000000       28.937071        41.000000    19.0
3  12.000000       16.000000        26.000000    13.0
4   2.000000       15.000000        36.741477     7.0

max_iter = 10
   R&D Spend  Administration  Marketing Spend  Profit
0   7.552527       15.000000        30.000000    11.0
1   4.000000        5.000000        20.000000     9.0
2  15.000000       28.937071        41.000000    19.0
3  12.000000       16.000000        26.000000    13.0
4   2.000000       15.000000        36.741477     7.0

/home/zaid/.venv/lib/python3.12/site-packages/sklearn/impute/_iterative.py:867: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

In [139]:
from sklearn.ensemble import RandomForestRegressor

In [140]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.ensemble import RandomForestRegressor

imp = IterativeImputer(
    estimator=RandomForestRegressor(
        n_estimators=100,
        random_state=0
    ),
    random_state=0
)

df_rf = pd.DataFrame(
    imp.fit_transform(df),
    columns=df.columns,
    index=df.index
)

print(df_rf)

    R&D Spend  Administration  Marketing Spend  Profit
21       6.92           15.00            30.00    11.0
37       4.00            5.00            20.00     9.0
2       15.00           14.91            41.00    19.0
14      12.00           16.00            26.00    13.0
44       2.00           15.00            25.19     7.0

In [141]:
imp1 = IterativeImputer(random_state=0)

df_br = pd.DataFrame(
    imp1.fit_transform(df),
    columns=df.columns,
    index=df.index
)

In [142]:
imp2 = IterativeImputer(
    estimator=RandomForestRegressor(random_state=0),
    random_state=0
)

df_rf = pd.DataFrame(
    imp2.fit_transform(df),
    columns=df.columns,
    index=df.index
)

In [143]:
print("Bayesian Ridge")
print(df_br)

print("\nRandom Forest")
print(df_rf)

Bayesian Ridge
    R&D Spend  Administration  Marketing Spend  Profit
21   7.552527       15.000000        30.000000    11.0
37   4.000000        5.000000        20.000000     9.0
2   15.000000       28.937071        41.000000    19.0
14  12.000000       16.000000        26.000000    13.0
44   2.000000       15.000000        36.741477     7.0

Random Forest
    R&D Spend  Administration  Marketing Spend  Profit
21       6.92           15.00            30.00    11.0
37       4.00            5.00            20.00     9.0
2       15.00           14.91            41.00    19.0
14      12.00           16.00            26.00    13.0
44       2.00           15.00            25.19     7.0

In [144]:
# Artificially remove known values:
df_original = df.copy()
df_missing = df_original.copy()

df_missing.loc[0, 'R&D Spend'] = np.nan
df_missing.loc[2, 'Marketing Spend'] = np.nan
df_missing.loc[4, 'Administration'] = np.nan

In [145]:
imp = IterativeImputer(random_state=0)

df_br = pd.DataFrame(
    imp.fit_transform(df_missing),
    columns=df.columns,
    index=df.index
)

ValueError: Shape of passed values is (7, 4), indices imply (5, 4)

In [ ]:
print(df.shape)
print(df_missing.shape)

(5, 4)
(7, 4)

In [ ]:
print(df.index)
print(df_missing.index)

Index([21, 37, 2, 14, 44], dtype='int64')
Index([21, 37, 2, 14, 44, 0, 4], dtype='int64')

In [ ]:
df_missing.loc[21, 'R&D Spend'] = np.nan
df_missing.loc[2, 'Marketing Spend'] = np.nan
df_missing.loc[44, 'Administration'] = np.nan

In [ ]:
df_missing = df.copy()

df_missing.iloc[0, 0] = np.nan
df_missing.iloc[2, 2] = np.nan
df_missing.iloc[4, 1] = np.nan

print(df_missing)

    R&D Spend  Administration  Marketing Spend  Profit
21        NaN            15.0             30.0    11.0
37        4.0             5.0             20.0     9.0
2        15.0             NaN              NaN    19.0
14       12.0            16.0             26.0    13.0
44        2.0             NaN              NaN     7.0

In [ ]:
imp = IterativeImputer(random_state=0)

df_br = pd.DataFrame(
    imp.fit_transform(df_missing),
    columns=df_missing.columns,
    index=df_missing.index
)

/home/zaid/.venv/lib/python3.12/site-packages/sklearn/impute/_iterative.py:867: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

In [ ]:
imp2 = IterativeImputer(
    estimator=RandomForestRegressor(random_state=0),
    random_state=0
)

df_rf = pd.DataFrame(
    imp2.fit_transform(df),
    columns=df.columns,
    index=df.index
)

In [ ]:
print("Bayesian Ridge")
print(df_br)

print("\nRandom Forest")
print(df_rf)

Bayesian Ridge
    R&D Spend  Administration  Marketing Spend  Profit
21   7.708016       15.000000        30.000000    11.0
37   4.000000        5.000000        20.000000     9.0
2   15.000000       23.067350        30.611651    19.0
14  12.000000       16.000000        26.000000    13.0
44   2.000000        5.283536        23.455130     7.0

Random Forest
    R&D Spend  Administration  Marketing Spend  Profit
21       6.92           15.00            30.00    11.0
37       4.00            5.00            20.00     9.0
2       15.00           14.91            41.00    19.0
14      12.00           16.00            26.00    13.0
44       2.00           15.00            25.19     7.0

In [ ]:
from sklearn.metrics import mean_squared_error

true = [
    df_original.iloc[0]['R&D Spend'],
    df_original.iloc[2][ 'Marketing Spend'],
    df_original.iloc[4][ 'Administration']
]

pred = [
    df_br.iloc[0][ 'R&D Spend'],
    df_br.iloc[2][ 'Marketing Spend'],
    df_br.iloc[4][ 'Administration']
]

mse = mean_squared_error(true, pred)

print(mse)

ValueError: Input contains NaN.

In [ ]:
print("True:", true)
print("Pred:", pred)

True: [np.float64(nan), np.float64(41.0), np.float64(15.0)]
Pred: [np.float64(7.708015622517509), np.float64(30.61165141840784), np.float64(5.283535788157341)]